package modelo;
// Generated Mar 1, 2021 11:14:13 PM by Hibernate Tools 4.3.1



/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private int idCategoria;
     private String nombreCategoria;
     private Double salarioBaseCategoria;
     private Double complementoCategoria;

    public Categorias() {
    }

	
    public Categorias(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categorias(int idCategoria, String nombreCategoria, Double salarioBaseCategoria, Double complementoCategoria) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.salarioBaseCategoria = salarioBaseCategoria;
       this.complementoCategoria = complementoCategoria;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Double getSalarioBaseCategoria() {
        return this.salarioBaseCategoria;
    }
    
    public void setSalarioBaseCategoria(Double salarioBaseCategoria) {
        this.salarioBaseCategoria = salarioBaseCategoria;
    }
    public Double getComplementoCategoria() {
        return this.complementoCategoria;
    }
    
    public void setComplementoCategoria(Double complementoCategoria) {
        this.complementoCategoria = complementoCategoria;
    }




}


