package modelo;
// Generated Mar 1, 2021 11:14:13 PM by Hibernate Tools 4.3.1



/**
 * Nomina generated by hbm2java
 */
public class Nomina  implements java.io.Serializable {


     private int idNomina;
     private Integer mes;
     private Integer anio;
     private Integer numeroTrienios;
     private Integer importeTrienios;
     private Float importeSalarioMes;
     private Float importeComplementoMes;
     private Float valorProrrateo;
     private Float brutoAnual;
     private Float irpf;
     private Float importeIrpf;
     private Float baseEmpresario;
     private Float seguridadSocialEmpresario;
     private Float importeSeguridadSocialEmpresario;
     private Float desempleoEmpresario;
     private Float importeDesempleoEmpresario;
     private Integer formacionEmpresario;
     private Integer importeFormacionEmpresario;
     private Integer accidentesTrabajoEmpresario;
     private Integer importeAccidentesTrabajoEmpresario;
     private Integer fogasaempresario;
     private Integer importeFogasaempresario;
     private Integer seguridadSocialTrabajador;
     private Integer importeSeguridadSocialTrabajador;
     private Integer desempleoTrabajador;
     private Integer importeDesempleoTrabajador;
     private Integer formacionTrabajador;
     private Integer importeFormacionTrabajador;
     private Integer brutoNomina;
     private Integer liquidoNomina;
     private Integer costeTotalEmpresario;
     private Integer idTrabajador;

    public Nomina() {
    }

	
    public Nomina(int idNomina) {
        this.idNomina = idNomina;
    }
    public Nomina(int idNomina, Integer mes, Integer anio, Integer numeroTrienios, Integer importeTrienios, Float importeSalarioMes, Float importeComplementoMes, Float valorProrrateo, Float brutoAnual, Float irpf, Float importeIrpf, Float baseEmpresario, Float seguridadSocialEmpresario, Float importeSeguridadSocialEmpresario, Float desempleoEmpresario, Float importeDesempleoEmpresario, Integer formacionEmpresario, Integer importeFormacionEmpresario, Integer accidentesTrabajoEmpresario, Integer importeAccidentesTrabajoEmpresario, Integer fogasaempresario, Integer importeFogasaempresario, Integer seguridadSocialTrabajador, Integer importeSeguridadSocialTrabajador, Integer desempleoTrabajador, Integer importeDesempleoTrabajador, Integer formacionTrabajador, Integer importeFormacionTrabajador, Integer brutoNomina, Integer liquidoNomina, Integer costeTotalEmpresario, Integer idTrabajador) {
       this.idNomina = idNomina;
       this.mes = mes;
       this.anio = anio;
       this.numeroTrienios = numeroTrienios;
       this.importeTrienios = importeTrienios;
       this.importeSalarioMes = importeSalarioMes;
       this.importeComplementoMes = importeComplementoMes;
       this.valorProrrateo = valorProrrateo;
       this.brutoAnual = brutoAnual;
       this.irpf = irpf;
       this.importeIrpf = importeIrpf;
       this.baseEmpresario = baseEmpresario;
       this.seguridadSocialEmpresario = seguridadSocialEmpresario;
       this.importeSeguridadSocialEmpresario = importeSeguridadSocialEmpresario;
       this.desempleoEmpresario = desempleoEmpresario;
       this.importeDesempleoEmpresario = importeDesempleoEmpresario;
       this.formacionEmpresario = formacionEmpresario;
       this.importeFormacionEmpresario = importeFormacionEmpresario;
       this.accidentesTrabajoEmpresario = accidentesTrabajoEmpresario;
       this.importeAccidentesTrabajoEmpresario = importeAccidentesTrabajoEmpresario;
       this.fogasaempresario = fogasaempresario;
       this.importeFogasaempresario = importeFogasaempresario;
       this.seguridadSocialTrabajador = seguridadSocialTrabajador;
       this.importeSeguridadSocialTrabajador = importeSeguridadSocialTrabajador;
       this.desempleoTrabajador = desempleoTrabajador;
       this.importeDesempleoTrabajador = importeDesempleoTrabajador;
       this.formacionTrabajador = formacionTrabajador;
       this.importeFormacionTrabajador = importeFormacionTrabajador;
       this.brutoNomina = brutoNomina;
       this.liquidoNomina = liquidoNomina;
       this.costeTotalEmpresario = costeTotalEmpresario;
       this.idTrabajador = idTrabajador;
    }
   
    public int getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(int idNomina) {
        this.idNomina = idNomina;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Integer getNumeroTrienios() {
        return this.numeroTrienios;
    }
    
    public void setNumeroTrienios(Integer numeroTrienios) {
        this.numeroTrienios = numeroTrienios;
    }
    public Integer getImporteTrienios() {
        return this.importeTrienios;
    }
    
    public void setImporteTrienios(Integer importeTrienios) {
        this.importeTrienios = importeTrienios;
    }
    public Float getImporteSalarioMes() {
        return this.importeSalarioMes;
    }
    
    public void setImporteSalarioMes(Float importeSalarioMes) {
        this.importeSalarioMes = importeSalarioMes;
    }
    public Float getImporteComplementoMes() {
        return this.importeComplementoMes;
    }
    
    public void setImporteComplementoMes(Float importeComplementoMes) {
        this.importeComplementoMes = importeComplementoMes;
    }
    public Float getValorProrrateo() {
        return this.valorProrrateo;
    }
    
    public void setValorProrrateo(Float valorProrrateo) {
        this.valorProrrateo = valorProrrateo;
    }
    public Float getBrutoAnual() {
        return this.brutoAnual;
    }
    
    public void setBrutoAnual(Float brutoAnual) {
        this.brutoAnual = brutoAnual;
    }
    public Float getIrpf() {
        return this.irpf;
    }
    
    public void setIrpf(Float irpf) {
        this.irpf = irpf;
    }
    public Float getImporteIrpf() {
        return this.importeIrpf;
    }
    
    public void setImporteIrpf(Float importeIrpf) {
        this.importeIrpf = importeIrpf;
    }
    public Float getBaseEmpresario() {
        return this.baseEmpresario;
    }
    
    public void setBaseEmpresario(Float baseEmpresario) {
        this.baseEmpresario = baseEmpresario;
    }
    public Float getSeguridadSocialEmpresario() {
        return this.seguridadSocialEmpresario;
    }
    
    public void setSeguridadSocialEmpresario(Float seguridadSocialEmpresario) {
        this.seguridadSocialEmpresario = seguridadSocialEmpresario;
    }
    public Float getImporteSeguridadSocialEmpresario() {
        return this.importeSeguridadSocialEmpresario;
    }
    
    public void setImporteSeguridadSocialEmpresario(Float importeSeguridadSocialEmpresario) {
        this.importeSeguridadSocialEmpresario = importeSeguridadSocialEmpresario;
    }
    public Float getDesempleoEmpresario() {
        return this.desempleoEmpresario;
    }
    
    public void setDesempleoEmpresario(Float desempleoEmpresario) {
        this.desempleoEmpresario = desempleoEmpresario;
    }
    public Float getImporteDesempleoEmpresario() {
        return this.importeDesempleoEmpresario;
    }
    
    public void setImporteDesempleoEmpresario(Float importeDesempleoEmpresario) {
        this.importeDesempleoEmpresario = importeDesempleoEmpresario;
    }
    public Integer getFormacionEmpresario() {
        return this.formacionEmpresario;
    }
    
    public void setFormacionEmpresario(Integer formacionEmpresario) {
        this.formacionEmpresario = formacionEmpresario;
    }
    public Integer getImporteFormacionEmpresario() {
        return this.importeFormacionEmpresario;
    }
    
    public void setImporteFormacionEmpresario(Integer importeFormacionEmpresario) {
        this.importeFormacionEmpresario = importeFormacionEmpresario;
    }
    public Integer getAccidentesTrabajoEmpresario() {
        return this.accidentesTrabajoEmpresario;
    }
    
    public void setAccidentesTrabajoEmpresario(Integer accidentesTrabajoEmpresario) {
        this.accidentesTrabajoEmpresario = accidentesTrabajoEmpresario;
    }
    public Integer getImporteAccidentesTrabajoEmpresario() {
        return this.importeAccidentesTrabajoEmpresario;
    }
    
    public void setImporteAccidentesTrabajoEmpresario(Integer importeAccidentesTrabajoEmpresario) {
        this.importeAccidentesTrabajoEmpresario = importeAccidentesTrabajoEmpresario;
    }
    public Integer getFogasaempresario() {
        return this.fogasaempresario;
    }
    
    public void setFogasaempresario(Integer fogasaempresario) {
        this.fogasaempresario = fogasaempresario;
    }
    public Integer getImporteFogasaempresario() {
        return this.importeFogasaempresario;
    }
    
    public void setImporteFogasaempresario(Integer importeFogasaempresario) {
        this.importeFogasaempresario = importeFogasaempresario;
    }
    public Integer getSeguridadSocialTrabajador() {
        return this.seguridadSocialTrabajador;
    }
    
    public void setSeguridadSocialTrabajador(Integer seguridadSocialTrabajador) {
        this.seguridadSocialTrabajador = seguridadSocialTrabajador;
    }
    public Integer getImporteSeguridadSocialTrabajador() {
        return this.importeSeguridadSocialTrabajador;
    }
    
    public void setImporteSeguridadSocialTrabajador(Integer importeSeguridadSocialTrabajador) {
        this.importeSeguridadSocialTrabajador = importeSeguridadSocialTrabajador;
    }
    public Integer getDesempleoTrabajador() {
        return this.desempleoTrabajador;
    }
    
    public void setDesempleoTrabajador(Integer desempleoTrabajador) {
        this.desempleoTrabajador = desempleoTrabajador;
    }
    public Integer getImporteDesempleoTrabajador() {
        return this.importeDesempleoTrabajador;
    }
    
    public void setImporteDesempleoTrabajador(Integer importeDesempleoTrabajador) {
        this.importeDesempleoTrabajador = importeDesempleoTrabajador;
    }
    public Integer getFormacionTrabajador() {
        return this.formacionTrabajador;
    }
    
    public void setFormacionTrabajador(Integer formacionTrabajador) {
        this.formacionTrabajador = formacionTrabajador;
    }
    public Integer getImporteFormacionTrabajador() {
        return this.importeFormacionTrabajador;
    }
    
    public void setImporteFormacionTrabajador(Integer importeFormacionTrabajador) {
        this.importeFormacionTrabajador = importeFormacionTrabajador;
    }
    public Integer getBrutoNomina() {
        return this.brutoNomina;
    }
    
    public void setBrutoNomina(Integer brutoNomina) {
        this.brutoNomina = brutoNomina;
    }
    public Integer getLiquidoNomina() {
        return this.liquidoNomina;
    }
    
    public void setLiquidoNomina(Integer liquidoNomina) {
        this.liquidoNomina = liquidoNomina;
    }
    public Integer getCosteTotalEmpresario() {
        return this.costeTotalEmpresario;
    }
    
    public void setCosteTotalEmpresario(Integer costeTotalEmpresario) {
        this.costeTotalEmpresario = costeTotalEmpresario;
    }
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }




}


