package modelo;
// Generated Mar 1, 2021 11:14:13 PM by Hibernate Tools 4.3.1



/**
 * Trabajadorbbdd generated by hbm2java
 */
public class Trabajadorbbdd  implements java.io.Serializable {


     private int idTrabajador;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String column5;
     private String nifnie;
     private String email;
     private String fechaAlta;
     private String codigoCuenta;
     private String iban;
     private Integer idEmpresa;
     private Integer idCategoria;

    public Trabajadorbbdd() {
    }

	
    public Trabajadorbbdd(int idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public Trabajadorbbdd(int idTrabajador, String nombre, String apellido1, String apellido2, String column5, String nifnie, String email, String fechaAlta, String codigoCuenta, String iban, Integer idEmpresa, Integer idCategoria) {
       this.idTrabajador = idTrabajador;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.column5 = column5;
       this.nifnie = nifnie;
       this.email = email;
       this.fechaAlta = fechaAlta;
       this.codigoCuenta = codigoCuenta;
       this.iban = iban;
       this.idEmpresa = idEmpresa;
       this.idCategoria = idCategoria;
    }
   
    public int getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(int idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getColumn5() {
        return this.column5;
    }
    
    public void setColumn5(String column5) {
        this.column5 = column5;
    }
    public String getNifnie() {
        return this.nifnie;
    }
    
    public void setNifnie(String nifnie) {
        this.nifnie = nifnie;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(String fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getCodigoCuenta() {
        return this.codigoCuenta;
    }
    
    public void setCodigoCuenta(String codigoCuenta) {
        this.codigoCuenta = codigoCuenta;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }




}


